name: Ndjson.AsyncStreams.AspNetCore.Mvc - CD
on:
  push:
    tags:
    - "aspnetcore-mvc-v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Extract VERSION
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/aspnetcore-mvc-v/}" >> $GITHUB_ENV
    - name: Setup .NET Core 3.1 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Setup .NET 5.0 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build
    - name: Pack
      run: dotnet pack --configuration Release --no-build
    - name: NuGet Push Ndjson.AsyncStreams.AspNetCore.Mvc
      run: dotnet nuget push Ndjson.AsyncStreams.AspNetCore.Mvc.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY}
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    - name: NuGet Push Ndjson.AsyncStreams.AspNetCore.Mvc.NewtonsoftJson
      run: dotnet nuget push Ndjson.AsyncStreams.AspNetCore.Mvc.NewtonsoftJson.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY}
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}