name: Ndjson.AsyncStreams.AspNetCore - CD
on:
  push:
    tags:
    - "aspnetcore-v[0-9]+.[0-9]+.[0-9]+"
permissions:
  contents: read
  id-token: write
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Extract VERSION
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/aspnetcore-v/}" >> $GITHUB_ENV
    - name: Setup .NET 8.0 SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '8.0.x'
    - name: Setup .NET 9.0 SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '9.0.x'
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build
    - name: Pack
      run: dotnet pack --configuration Release --no-build
    - name: Log in to NuGet
      uses: NuGet/login@v1
      id: nuget-login
      with:
        user: ${{ secrets.NUGET_USER }}
    - name: NuGet Push Ndjson.AsyncStreams.AspNetCore
      run: dotnet nuget push src/Ndjson.AsyncStreams.AspNetCore/bin/Release/Ndjson.AsyncStreams.AspNetCore.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY}
      env:
        NUGET_API_KEY: ${{ steps.nuget-login.outputs.NUGET_API_KEY }}