name: Ndjson.AsyncStreams.DocFx
on: workflow_dispatch
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Setup .NET 8.0 SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '8.0.x'
    - name: Setup .NET 9.0 SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '9.0.x'
    - name: Setup docfx
      run: dotnet tool update -g docfx
    - name: Restore .NET Projects
      run: dotnet restore
    - name: Build Documentation Artifact
      run: docfx docs/docfx.json
    - name: Upload Documentation Artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: 'docs/_artifact'
    - name: Deploy Documentation Artifact to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4